### ISSUE TITLE
Rework of alpine version tagging for docker images

### ISSUE THREAD

**Issue by AlexisPPLIN** [willfarrell/docker-autoheal#114]
The current docker image uses `alpine:3.18.3` which is not the best for security updates.
Maybe it's time to provide more docker images tags.

I would suggest something like this : 
- Latest alpine version : `latest`, `1.3.0`
- Major alpine version : `1.3.0-alpine3`
- Minor alpine version : `1.3.0-alpine3.17`,  `1.3.0-alpine3.18`

I do not feel the necessity to give a "Patch alpine version". Maybe I'm wrong.

**Comment by christiantosta** [comment]
Opened a pull request here: https://github.com/willfarrell/docker-autoheal/pull/115
