### ISSUE TITLE
License

### ISSUE THREAD

**Issue by charlyinalbon** [willfarrell/docker-autoheal#16]
Hi
I really like the project! :-)
However, I cannot find a license file. In order for me to reuse your project, it must have a license file. 
Best suitable for me would be an MIT, BSD or Apache 2.0 license. ;-)
What do you think? Is there any plan to add a license?
Cheers
Michael

**Comment by willfarrell** [comment]
Thanks for asking first. It's now officially MIT, enjoy.

**Comment by charlyinalbon** [comment]
Wow! Thanks! That was quick!
