### ISSUE TITLE
ARM support (multi-arch manifest) not working?

### ISSUE THREAD

**Issue by Codelica** [willfarrell/docker-autoheal#26]
I see code and a couple closed issues (#19, #14) about ARM support, but pulling willfarrell/autoheal on an ARM device like a Raspberry Pi results in the x86_64 image being downloaded:

![onyx 2019-02-12 10-00-48](https://user-images.githubusercontent.com/386101/52653580-6ded5100-2ead-11e9-924e-34f077292cbe.png)

Inspecting the manifest doesn't seem to include manifest platform info as expected (compared to MongoDB):

![onyx 2019-02-12 10-19-48](https://user-images.githubusercontent.com/386101/52654699-ccb3ca00-2eaf-11e9-8541-c75a6a2b07e0.png)

Not sure if I'm overlooking something, but the the muti-arch portion of the build seems to be broken?

Thanks for reading...

EDIT:  I found another tool for checking the manifest:

![onyx 2019-02-12 10-29-41](https://user-images.githubusercontent.com/386101/52655345-2ec0ff00-2eb1-11e9-96ce-782db5e0bad3.png)

**Comment by willfarrell** [comment]
Everything above is correct. The code change only supports the ability to have multi-arch (ie build yourself). It's on my list to update the CI/CD to build for the different platforms and push to docker hub. I hope to get to this in March, just been busy finishing off a big project.

**Comment by willfarrell** [comment]
Check out [build.sh](https://github.com/willfarrell/docker-autoheal/blob/master/build.sh), that connects into the 2 ci sample templates. It was written by a contributor. I haven't had a chance to dig into it and deploy a CI/CD myself to have these pre-build for everyone. I will make some time soon to get this put together and deployed. Watch out for a PR.

**Comment by grewhit25** [comment]
Excellent! 
Looking forward to your multi-arch solution, I need to auto heal one of my standalone container.

**Comment by Kampe** [comment]
Any news on this?

**Comment by pschmitt** [comment]
I tackled this using GitHub Actions and docker buildx.
See [my fork](https://github.com/pschmitt/docker-autoheal).
The image are published here: [pschmitt/autoheal](https://hub.docker.com/repository/docker/pschmitt/autoheal/tags?page=1)
I might issue some PRs soon (if I don't forget or loose interest).

**Comment by giejay** [comment]
@pschmitt Thanks! I build an ARM image of your fork and it seems to work!

**Comment by pschmitt** [comment]
@giejay great to hear that. If your are not trying to customize the container you can also directly use the aforementioned `pschmitt/autoheal`. It's a true multiarch image ;)

**Comment by QuietKerb** [comment]
Thanks @pschmitt 

I was getting this error on Raspbian when running or building autoheal:
`standard_init_linux.go:190: exec user process caused "exec format error"`

switching to `pschmitt/autoheal` *just works*  :+1:

**Comment by willfarrell** [comment]
Apologies on the delay, been a crazy year. All of @pschmitt PRs have been merged, also invited him to be a contributor. 
Will be minting a new version soon.
