### ISSUE TITLE
DOCKER_SOCK not changeable

### ISSUE THREAD

**Issue by luckydonald** [willfarrell/docker-autoheal#3]
Heya.
Currently the socket is [hardcoded](https://github.com/willfarrell/docker-autoheal/blob/4a30bca3668fd80d578bb5d74e351dfcbd7e299f/docker-entrypoint#L4) to be `/tmp/docker.sock`.

I'd like to change it to the default `/var/run/docker.sock`.

So I propose replacing the line with

```
DOCKER_SOCK=${DOCKER_SOCK:-/var/run/docker.sock}
```

That way it is settable via environment variables,
and the original `/tmp/docker.sock` is still possible.

**Comment by luckydonald** [comment]
On a side note, it will still show `/docker-entrypoint: exec: line 46: autoheal: not found` if the socket file does not exist.

**Comment by willfarrell** [comment]
Merged. Can you test it out and let me know.

**Comment by luckydonald** [comment]
Seems to be working 👍
