### ISSUE TITLE
Use DOCKER_HOST instead of mounting /var/run/docker.sock

### ISSUE THREAD

**Issue by oldirtybasti** [willfarrell/docker-autoheal#43]
Hi,

thanks for that great tool.

I think it would be better to communicate with the docker daemon via the DOCKER_HOST variable instead of /var/run/docker.sock - you then do not have to mount a volume and health checking on other hosts would also be possible.

**Comment by Alek-Zywot** [comment]
@oldirtybasti , you can use the env variable `DOCKER_SOCK` to set the docker socket. 
See issue #3 for more details.
