### ISSUE TITLE
Unrecognized input header error in 1.1.0

### ISSUE THREAD

**Issue by derekn** [willfarrell/docker-autoheal#55]
Updated to latest v1.1.0 and container exits immediately with "Unrecognized input header: 99" error. rolling back to 1.0.0 works fine.

Server Version: 18.09.8

**Comment by hasnat** [comment]
now with #54 
my gut says some status we're requesting, don't exist in 1.18 API ( https://docs.docker.com/engine/api/v1.18/#21-containers ),
@willfarrell rollback?

**Comment by willfarrell** [comment]
rollback complete.

**Comment by willfarrell** [comment]
Thanks for reporting.
