### ISSUE TITLE
Why is there a daily job for building the docker image?

### ISSUE THREAD

**Issue by reconman** [willfarrell/docker-autoheal#57]
I noticed that https://containrrr.dev/watchtower/ updates autoheal every day.

The github CI workflow contains a cron schedule to trigger a docker build every day, addtionally to every push to master and every tag.

This definitely seems like overkill. Why do you need to build daily if the container content doesn't change every day? Wouldn't the build on every push to master be enough?

**Comment by willfarrell** [comment]
This is to catch any security updates in the base image or dependencies. I personally would not recommend using `latest` in production, or `watchtower` for that matter. Bad updates can happen.

If watchtower is replacing the container even when the image layers have the same checksums you should file a bug with them.
