### ISSUE TITLE
Container stuck in "mkdir $TMP_DIR"

### ISSUE THREAD

**Issue by jmfederico** [willfarrell/docker-autoheal#6]
Can't really say why, but today I had an issue with a docker-autoheal container that got stuck on an infinite loop because it couldn't go past "```mkdir $TMP_DIR```" in [docker-entrypoint](https://github.com/willfarrell/docker-autoheal/blob/f638dd81d2dd7087e1175d758285362aed4f3038/docker-entrypoint#L9) saying it already existed.

I am running it with ```restart: always``` using docker-compose.

I am tempted to change that line to ```mkdir -p $TMP_DIR```

Is there any reason why it doesn't check if the directory exists already, or why it shouldn't just continue in case it does?

**Comment by willfarrell** [comment]
I never had my contain restart happen, which would maintain the tmp dir - causing the issue your're having. Thanks for the issue report. I've update the script to reflect this.
