### ISSUE TITLE
Add Pushbullet support

### ISSUE THREAD

**Issue by colemamd** [willfarrell/docker-autoheal#60]
Add [Pushbullet](https://github.com/caronc/apprise/wiki/Notify_pushbullet) support.

Assignees: 
Labels: feature

**Comment by willfarrell** [comment]
Proprietary integrations will not be included in this project. Sorry. You're welcome to post a link to your implementation here for others to find.

**Comment by colemamd** [comment]
My apologies! This was opened by mistake. Meant to be on my fork!

**Comment by willfarrell** [comment]
all good.
