### ISSUE TITLE
Do you still own the docker hub account?

### ISSUE THREAD

**Issue by yegle** [willfarrell/docker-autoheal#62]
I've noticed the docker image `:latest` label is updated very frequently. Since the image is manually pushed (instead of using autobuild https://docs.docker.com/docker-hub/builds/link-source/) I have no idea whether it's actually from you.

Can you set up auto build so that we know the image is indeed built from this repo? I see the last auto build was from 2 years ago: https://hub.docker.com/r/willfarrell/autoheal/builds

**Comment by willfarrell** [comment]
Yes, I still own the docker account. Builds were moved from Docker Hub to GitHub. See https://github.com/willfarrell/docker-autoheal/actions

**Comment by yegle** [comment]
Ah cool! Thank you!

You may want to add this information to the README :-)
