### ISSUE TITLE
Update to alpine 3.13

### ISSUE THREAD

**Issue by husim0** [willfarrell/docker-autoheal#63]
Hello,

Could you please update your image to alpine 3.13 ?

Thank you

**Comment by willfarrell** [comment]
Would you like to put a PR together?

**Comment by coheigea** [comment]
@willfarrell Would it be possible to get a release out even based on the current Alpine 3.11.11 to fix some high security vulnerabilities? Using trivy I see:

willfarrell/autoheal:1.1.0 (alpine 3.11.8)
==========================================
Total: 9 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 7, CRITICAL: 0)

whereas:

willfarrell/autoheal:latest (alpine 3.11.11)
============================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
