### ISSUE TITLE
Could not do a head request for "willfarrell/autoheal:latest", ...

### ISSUE THREAD

**Issue by redstormsju** [willfarrell/docker-autoheal#95]
Got this notification after watchtower tried updating my container....anyone else seeing this? Any way to resolve?

"Could not do a head request for "willfarrell/autoheal:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present" "

**Comment by oliverlevay** [comment]
We have the same problem suddenly

**Comment by redstormsju** [comment]
Supposedly it's a big in the docker build app.

**Comment by 01ste02** [comment]
Could you link a github issue for that docker build-bug? @redstormsju

**Comment by redstormsju** [comment]
> Could you please link a github issue for that docker build-bug? @redstormsju 

I haven't found one but that's what's been referenced insomne of the posts about this issue.
